install.packages("twitteR")
install.packages(c("ROAuth","RCurl"))
install.packages("httr")
library(httr)
require("ROAuth")
require("RCurl")
library(twitteR)
options(httr_oob_cache=T)
Sys.setenv(BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAAJQmQAEAAAAA%2BJXV%2FgVqZYncxNXKLIFOMkf7uC0%3DKjHpnLIpFdKLG4JhP43PzFhdH4wt1sIjz9qORnJtBfyqLPLu47")
install.packages("jsonlite")
install.packages("dplyr")
require(httr)
require(jsonlite)
require(dplyr)
bearer_token<-Sys.getenv("AAAAAAAAAAAAAAAAAAAAAJQmQAEAAAAA%2BJXV%2FgVqZYncxNXKLIFOMkf7uC0%3DKjHpnLIpFdKLG4JhP43PzFhdH4wt1sIjz9qORnJtBfyqLPLu47")
headers<-c("Authorization"=sprintf("Bearer %s",bearer_token))
params<-list("user.fields")
install.packages("rtweet")
installed.packages("ggplot2")
library("rtweet")
library("ggplot2")
library(dplyr)
install.packages("tidytext")
library(tidytext)
PalestineTws<- search_tweets2(q="#Palestine", n=10000,
                                lang="en",
                                include_rts=FALSE)
IsraelTws<- search_tweets(q="Israel",n=10000,
                          lang="en",
                          include_rts = FALSE)
